# Generated by Django 4.0.6 on 2022-08-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.guild'),
        ),
    ]
