# Generated by Django 4.0.6 on 2022-08-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_referent_member'),
        ('event', '0002_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='engaged_members',
            field=models.ManyToManyField(to='member.member'),
        ),
    ]
