# Generated by Django 4.0.6 on 2022-08-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_referent_member'),
        ('event', '0003_event_engaged_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='engaged_members',
            field=models.ManyToManyField(blank=True, to='member.member'),
        ),
    ]
