# Generated by Django 4.0.6 on 2022-08-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_member_origin'),
        ('event', '0009_event_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.guild'),
        ),
    ]
