# Generated by Django 4.0.6 on 2022-08-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open_for_registrations',
            field=models.BooleanField(default=True),
        ),
    ]
